def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    
    environment {
        cluster = "vpro-app-prod"
        service = "vprofile-app-task-service-prod"
    }

    stages {
        stage("Deploy to Staging ECS") {
            steps {
                withAWS(credentials: 'aws-credential', region: 'ap-northeast-1') {
                    script {
                        sh "aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment"
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkins-cicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}